### PR TITLE
Create `dependabot.yml`

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Signed-off-by: Mathieu Benoit <mathieu-benoit@hotmail.fr>

In order to get the dependencies up-to-date, once this PR merged in `main`, adding the `dependabot.yml` file.

I checked that this tool and this definition was already in use with another sigstore project there as an example: https://github.com/sigstore/rekor/blob/main/.github/dependabot.yml

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
FYI: CI (`golangci-lint`) issue because of https://github.com/sigstore/cosign-gatekeeper-provider/pull/23.

**Comment by mathieu-benoit** [comment]
CI now fixed, ready for your review, thanks!

**Review by dlorenc — APPROVED** [review]

**Comment by mathieu-benoit** [comment]
JFYI: there is not that much PR opened by dependabot once merge into `main` branch, here is what it will generate as an illustration in my own fork: https://github.com/mathieu-benoit/cosign-gatekeeper-provider/pulls?q=is%3Apr+label%3Adependencies+

**Review by Dentrax — APPROVED** [review]
Thanks!

PR #26 also updates `go.mod` dependencies, let's prioritize it first to not get conflict with depandabot and to not break the pipeline due to minimum go version requirements of some packages.

**Review by Dentrax — APPROVED** [review]

**Pull request merged**
